services:
  dev-host:
    build:
      context: ./dev-host
      dockerfile: Dockerfile
    container_name: dev-host
    hostname: dev-host
    ports:
      - '2223:22'
      - '${DEV_HOST_HTTP_PORT:-3100}:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/workspace
    networks:
      - chaba

networks:
  chaba:
    name: chaba
