services:
  dev-host:
    build:
      context: ./dev-host
      dockerfile: Dockerfile
    container_name: ${DEV_HOST_CONTAINER_NAME:-dev-host}
    hostname: ${DEV_HOST_HOSTNAME:-dev-host}
    ports:
      - '${DEV_HOST_SSH_PORT:-2223}:22'
      - '${DEV_HOST_HTTP_PORT:-3100}:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/workspace
    networks:
      - chaba

networks:
  chaba:
    name: chaba
