services:
  dev-host:
    build:
      context: ./dev-host
      dockerfile: Dockerfile
    container_name: dev-host
    hostname: dev-host
    ports:
      - '2223:22'
      - '80:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/workspace
    command: /usr/sbin/sshd -D
    networks:
      - chaba

networks:
  chaba:
    name: chaba
